### ISSUE TITLE
140 Max daily IP views reached, please log into YouTube (English Lang.) With an active channel to continue

### ISSUE THREAD

**Issue by Fechin** [xiaokaixuan/vagex-robot#2]
第二天看日志出现这个错误：
Tip: Error detected: 140 Max daily IP views reached, please log into YouTube (English Lang.) With an active channel to continue

**Comment by xiaokaixuan** [comment]
![image](https://user-images.githubusercontent.com/7234473/56780669-d1cbb880-6812-11e9-8f54-a3f481f85190.png)
![image](https://user-images.githubusercontent.com/7234473/56780788-4141a800-6813-11e9-9ccb-6800f92fbe3d.png)

**Comment by Fechin** [comment]
好，非常感谢！
